### ISSUE TITLE
Unable to assign work item

### ISSUE THREAD

**Issue by dmbaio** [tfsaggregator/aggregator-cli#101]
I'm unsure if this is a bug or if I'm simply doing it wrong. I have been trying various methods for the past few days. The rule language document states "Use the DisplayName property to assign a user."

Whenever I attempt something like this...
> self.AssignedTo.DisplayName = "First Last";

...I get an error of "Object reference not set to an instance of an object" if the item is currently unassigned, and if it IS already assigned to someone I get no error but it does not update this field. If it is indeed possible to set this field, what is the correct syntax for doing so?

**Comment by BobSilent** [comment]
If the work item is not yet assigned, `self.AssignedTo` is `null`.

In my usecases I often had a valid identity from e.g. `selfUpdate` or `self` itself.
If you do not have an Identity you need a unique ID, e.g. email address to create one. Then you can do

```csharp
self.AssignedTo = new IdentityRef() { UniqueName = "a@b.com" };
```

Just from my mind, did not test it right now.

**Comment by dmbaio** [comment]
Unfortunately that still fails with the same "Object reference not set to an instance of an object" error. I tried with both UniqueName and DisplayName and neither worked.

**Comment by BobSilent** [comment]
can you please check something: 
the work item you want to update, can you please call this 

`https://dev.azure.com/{organization}/{project}/_apis/wit/workitems?ids={id}&fields=System.AssignedTo&api-version=5.1`

and replace `{organization}`, `{project}` with your valid valuesa and `{id}` with the work item id.

can you then check the json value of `System.AssignedTo` it should neither be `null` nor a simple `string` value

**Comment by dmbaio** [comment]
That field does not appear in the response.

**Comment by BobSilent** [comment]
Can you post your rule code?

**Comment by dmbaio** [comment]
`if (self.Id == 53429)
{
    self.AssignedTo = new Microsoft.VisualStudio.Services.WebApi.IdentityRef()
    {
        DisplayName = "MyFirst MyLast"
    };
}`

**Comment by BobSilent** [comment]
ok, not so much code which can go wrong.

> ```cs
> if (self.Id == 53429)
> {
>     self.AssignedTo = new Microsoft.VisualStudio.Services.WebApi.IdentityRef()
>     {
>         DisplayName = "MyFirst MyLast"
>     };
> }
> ```

Are these assumptions right: 
1. This code does **NOT** throw `NullReference` Exception.
2. Running the Rule, throws no Error/Warning.
3. Assigned to field is not changed for work item 53429.

**Comment by dmbaio** [comment]
That rule code now works after I built and deployed from your latest commit. It works both for changing existing assignment and for setting an assignment if it was unassigned.
