### ISSUE TITLE
Running 0.9.8 features to work without issues #91 and #92

### ISSUE THREAD

**Issue by ericbehughes** [tfsaggregator/aggregator-cli#111]
# Steps to reproduce
Install 0.9.8 instance using netcore 3.1 with resource version 1

# Bug
Using resource version 5.1-preview.3 works, but we want to learn how to upgrade our aggregator-cli to latest and use all the features without the issues above.

>Is this still a work in progress? 
>How can we combine the workarounds to #91 and #92 for version 0.9.8 because it has features that we want

## Environment
>NetCore 3.1
>Aggregate-cli 0.9.8

**Comment by BobSilent** [comment]
can be closed as new version is released?!
