### ISSUE TITLE
Triggered Bug DevOps items cause an error of "Input string was not in a correct format"

### ISSUE THREAD

**Issue by RSMJreck** [tfsaggregator/aggregator-cli#114]
# Steps to reproduce

Setup a rule for all work item types and then trigger it from DevOps using a type of 'Bug' (others probably work for this as well).

## Expected behavior

Rule executes and a status of 200 is returned.

## Actual behavior

Rule '<name>' failed: Input string was not in a correct format.
I've been able to look into this a little and it appears there are different 'fields' in the event from DevOps for a bug than for a Task/User Story/Feature. A mismatch of ILogger arguments seems to be the cause.

## Diagnostic logs

Event and requests
[bug troubleshoot.txt](https://github.com/tfsaggregator/aggregator-cli/files/4411378/bug.troubleshoot.txt)

## Environment

9,0 + 108PR items from SilentBob merged and deployed into Azure

**Comment by BobSilent** [comment]
can you please retry with [v0.9.9](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.9)

**Comment by RSMJreck** [comment]
Since installing 0.9.9, I haven't seen the error resurface so it appears that release fixed it. Thanks!
