### ISSUE TITLE
Document required PAT permissions

### ISSUE THREAD

**Issue by WilliamRitson** [tfsaggregator/aggregator-cli#133]
The documentation mentions what role the service principal needs but as far as I can tell it doesn't say what permissions the ADO PAT requires.

It would be nice to document the minimum permissions that the PAT requires so the aggregator can be set up in line with the principle of least privilege.

**Comment by RSMJreck** [comment]
The document at https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/setup.md covers what scopes the PAT needs.

**Comment by WilliamRitson** [comment]
Thanks. That answers my question. I think it may be valuable to link to that page from thre readme https://github.com/tfsaggregator/aggregator-cli/blob/master/README.md

**Comment by giuliov** [comment]
I have an idea to refactor and publish this material on <https://tfsaggregator.github.io/> wiki-style so you can improve it. Do you, @WilliamRitson, it would be a good idea ?

**Comment by WilliamRitson** [comment]
@giuliov That could be helpful and make it small changes to the wiki. But the documentation itself looks pretty good to me, my issue was I didn't notice that there was more documentation beyond what was linked to by the readme. So just adding a link to it could help.

**Comment by giuliov** [comment]
Can you take a look at https://tfsaggregator.github.io/docs/v3/

**Comment by WilliamRitson** [comment]
It looks good to me @giuliov one small nitpick there seem to be some broken images on the page https://tfsaggregator.github.io/docs/v3/setup/production/

**Comment by giuliov** [comment]
good catch, fixed, thanks.
