### ISSUE TITLE
Allow querying "tested by" links

### ISSUE THREAD

**Issue by denious** [tfsaggregator/aggregator-cli#141]
# Feature Request

I was trying to create a flow around User Story related Test Cases and automating QA work but could not find a way to query Test Cases and their states from the "links updated" event.

It would be great to have another property called TestedBy, for example, that would function the same way Children does right now.

**Comment by me1986au** [comment]
Hey Can you please bring back your blog for 

blog.denious.net/azure-b2c-role-based-authorization-part-1/
blog.denious.net/azure-b2c-role-based-authorization-part-2/

or provide another way to get to it

**Comment by giuliov** [comment]
You can do this today with a rule like this

```c#
// assume self is a 'User Story'
var allTests = new List<string>();
foreach(var testedByLink in self.RelationLinks.Where(link => link.Rel == "Microsoft.VSTS.Common.TestedBy-Forward"))
{
    var testCase = store.GetWorkItem(testedByLink);
    allTests.Add( $"{testCase.Id.Value} - {testCase.Title}" );
}
return String.Join(",\r\n", allTests);
```

Maybe you ask for a convenience field that hides the string constant?

**Comment by denious** [comment]
Thanks, this is perfect! No need to hide the string, but some documentation (or a link to the official documentation) on which strings are available would've solved my problem. I simply couldn't figure out which relationship to use.
