### ISSUE TITLE
IdentifyRef field type: Unable to cast object of type 'Microsoft.VisualStudio.Services.WebApi.IdentityRef' to type 'System.String'. 

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#15]
Unable to cast object of type 'Microsoft.VisualStudio.Services.WebApi.IdentityRef' to type 'System.String'.    at aggregator.Engine.WorkItemWrapper.GetFieldValue[T](String field) in D:\Repos\aggregator-cli\src\aggregator-ruleng\WorkItemWrapper.cs:line 412at aggregator.Engine.WorkItemWrapper.get_AssignedTo()

Then when trying to case like 
string assigned = ((Microsoft.VisualStudio.Services.WebApi.IdentityRef)self["AssignedTo"])?.DisplayName ?? "";

throws 
 type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft'

Need update
public IdentityRef AssignedTo

        {

            get { return GetFieldValue<IdentityRef>(CoreFieldRefNames.AssignedTo); }

            set { SetFieldValue(CoreFieldRefNames.AssignedTo, value); }

        }
and also Roslyn reference updates for types.

**Comment by giuliov** [comment]
Try 6c657b1c85dc18c4be1d779f9eaa80136a92b4a6

**Comment by pswetz** [comment]
Seems to be fixed in latest push
