### ISSUE TITLE
Relation navigators on WorkItemWrapper should return null if not present

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#17]
Something like item.Parent will throw an exception if there is no parent linked work item. Should just return null for reference checking. Currently have to check the link version of the field before calling the primary.

item.Parent
item.Children

**Comment by pswetz** [comment]
This returns WorkItemWrapper.Children param as empty array (IEnum) and WorkItemWrapper.Parent param as null if none exist.

**Comment by giuliov** [comment]
merged in develop branch
