### ISSUE TITLE
Getting 500 Internal error

### ISSUE THREAD

**Issue by prashanthbv12** [tfsaggregator/aggregator-cli#173]
everything was working fine till now from past six months and i did not download/update latest release
Today i did some tweaks in the rule as per the new requirement  and uploaded modified rule file and saw some function run time error. So I downloaded latest package and compiled latest version from local and uploaded latest rule file.
Now I am getting 500 Internal error. Any suggestions Please.

Error

run.csx(15,31): error CS1061: 'HttpRequest' does not contain a definition for 'GetWebHookEvent' and no accessible extension method 'GetWebHookEvent' accepting a first argument of type 'HttpRequest' could be found (are you missing a using directive or an assembly reference?)

run.csx(3,1): error CS0006: Metadata file '../bin/aggregator-webshared.dll' could not be found

**Comment by giuliov** [comment]
That is fixed in commit dea35e110ded4e5df771b1972ea88aea0555e5d0, part of release [v1.0.0-beta2.1](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v1.0.0-beta2.1)

**Comment by prashanthbv12** [comment]
Its working, Thank you
