### ISSUE TITLE
AGGREGATOR_NEW_VERSION_CHECK_DISABLED=1 - How does it work?

### ISSUE THREAD

**Issue by jprettyman** [tfsaggregator/aggregator-cli#187]
I found documentation for the following setting:
`AGGREGATOR_NEW_VERSION_CHECK_DISABLED=1`
My issue is, I have no idea how to implement this. It speaks of an environment but I am clueless on how to adjust this.

At times updates are provided and and I would like to control when they are delivered. Updating a rule in production must not update the engine unless I have performed testing to ensure all things work.

**Comment by giuliov** [comment]
Good question as the information is a bit sparse in the documentation.

One component is the CLI which manages the Azure Function, the other component is the Rule interpreter runtime uploaded in the Azure Function (see <https://tfsaggregator.github.io/docs/v3/design/>).
The `AGGREGATOR_NEW_VERSION_CHECK_DISABLED` controls the initial CLI check to update itself; it has no effect on the Interpreter runtime. The disable flag aims at air-gapped scenario where external are blocked; one use the CLI to validate rules and setup the mappings to a dockerised Aggregator instance.

You want to understand how to control the Rule interpreter runtime version.
The simplest way is through the `--requiredVersion` option supported by the `install.instance`, `update.instance`, and `update.rule` commands.
Another way is to specify the `--sourceUrl` option: it accepts both `http:` and `file:` URIs. This option permits to use custom built version of the runtime.

Let me know if this clarifies: I will add the explanation to the docs.

**Comment by jprettyman** [comment]
OK. My issue must be in getting the format correct for the --requiredVersion. I tried this before and whatever I put in there seemed to be ignored. Likely because I did not get the version identified correctly.
when I tried before, I keyed in an older version that was already installed and it upgraded anyway.
An example including an example version would be very helpful.

**Comment by giuliov** [comment]
See this example: [Create the Aggregator Instance (intermediate)](https://tfsaggregator.github.io/docs/v3/commands/command-examples/#create-the-aggregator-instance-intermediate).
