### ISSUE TITLE
New task: Code in documentation does not work

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#19]
This code throws exception, taken from documentation.

var parent = self;
var newChild = store.NewWorkItem("Task");
newChild.Title = "Brand new child";
parent.Relations.AddChild(newChild);

return parent.Title;

**Comment by pswetz** [comment]
[Information] Found a request for a new Task workitem in
[Error] Save failed:

After discussion issue is likely workitemstore line 177 and 277 usage of RuleContext.TeamProject parameter from request is not populated (and not what should be used).

**Comment by giuliov** [comment]
Should be fixed in 0.4.2

**Comment by pswetz** [comment]
New error logged in #21 when testing this.

**Comment by giuliov** [comment]
This is merged in master
