### ISSUE TITLE
Can we copy picklist values dynamically from one field to Other

### ISSUE THREAD

**Issue by prashanthbv12** [tfsaggregator/aggregator-cli#191]
Hello,

Whenever a certain values are selected from pick list is it possible to dynamically copy those values to another picklist field using this tool. If yes, please give a suggestion how to do it. Thanks in advance

**Comment by giuliov** [comment]
Short answer: no. 

As @jessehouwing  said:

> It runs on the server and is always one save away from the UI.
> It can do fancy calculations the rules engine won't allow and can work across hierarchies and queries (which the built-in rules won't allow), but needs a round-trip to the server. Thus it is only reactive and may need a UI refresh for calculations to show up.
> It cannot be used to block updates either. The data has already been saved once the aggregator runs. You could do compensating changes, but can't prevent them.
> When aggregator changes a value, it will also invoke itself once more (it runs on every change), so rules must run idempotent.

**Comment by prashanthbv12** [comment]
> Short answer: no.
> 
> As @jessehouwing said:
> 
> > It runs on the server and is always one save away from the UI.
> > It can do fancy calculations the rules engine won't allow and can work across hierarchies and queries (which the built-in rules won't allow), but needs a round-trip to the server. Thus it is only reactive and may need a UI refresh for calculations to show up.
> > It cannot be used to block updates either. The data has already been saved once the aggregator runs. You could do compensating changes, but can't prevent them.
> > When aggregator changes a value, it will also invoke itself once more (it runs on every change), so rules must run idempotent.

This means can I can create a pick list with values A,B,C and save work item first. And then can i have a rule to trigger copy the values A,B,C from first picklist to another picklist.

**Comment by jessehouwing** [comment]
Standard WIT rules can copy from one field to another within the same WI. You don't need Aggregator for that.
