### ISSUE TITLE
An error occurred during a cryptographic operation.

### ISSUE THREAD

**Issue by digitalanalogue9** [tfsaggregator/aggregator-cli#192]
# Steps to reproduce
Installed older version of aggregator-cli  (Aggregator CLI 0.9.1+3.Branch.master.Sha.8437ff414ecfd46da66ef5d3161f58818d9ab308)

Run dotnet aggregator-cli.dll update.instance --instance LLAggregatorTest --resourceGroup LLAggregatorTest

## Expected behavior
Updates to v.1.0.0.0 (v3 Azure Function)
## Actual behavior
It appears to fail maybe pulling the latest release from github ?

## Diagnostic logs
[2020-10-21 12:24:31Z] located a cached GitHub version query response
[2020-10-21 12:24:31Z] Cached versions are recent enough to not require checking GitHub
[2020-10-21 12:24:31Z] Found v1.0.0 on 18/09/2020 07:18:33 +00:00 in GitHub.
[2020-10-21 12:24:32Z] aggregator-cli v1.0.0 (build: 1.0.0.0 Release) (c) Copyright © TFS Aggregator Team
[2020-10-21 12:24:32Z] An error occurred during a cryptographic operation.

## Environment
Behind corporate firewall might be an issue ? 
0.91 -> 1.0.0

**Comment by giuliov** [comment]
After the banner (4th log line) Aggregator:

- parses the command line, and can't fail with that error
- builds the context.

This latter use `Microsoft.AspNetCore.DataProtection` to decrypt the logon credentials and it is the only thing that may cause that error. Why? Well, could be a few things.
One is a bug in Aggregator: I forgot to change the purpose string in the `IDataProtectionProvider.CreateProtector` call, it might conflict with other apps on the same machine.
Another may be the machine keys was never setup on the machine where Aggregator runs.
