### ISSUE TITLE
Random Error: Log is being used by another process

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#20]
Not consistent error, mostly seems to happen after an initial function app warmup but is inconsistent.

 [Warning] Rule '[RuleName]' failed: An error occurred while writing to logger(s). (The process cannot access the file 'D:\home\LogFiles\Application\Functions\Function\[RuleName]\2018-11-19T20-41-00Z-60d3d534f7.log' because it is being used by another process.)

**Comment by giuliov** [comment]
This should be resolved by #43 . Solving that, we can close this one too.
