### ISSUE TITLE
DevOps Service Hooks Queued but not Processing

### ISSUE THREAD

**Issue by ajardolino3** [tfsaggregator/aggregator-cli#205]
Is anyone having issues with TFS Aggregator service hooks getting stuck in queued?  We started using the TFS Aggregator with Azure DevOps and an Azure DevOps function about a month or so ago, and everything was working until around Wed, when we started noticing items continually being queued up but never processing.  Some are stuck in the queue as much as 24 hours, which is causing issues with our DevOps automations and workflow we created with TFS Aggregator.  Anyone know how to fix this, or know what is going on?  We literally have hundreds of devops items that are queued up.  New changes also get queued and do not process.  Some are randomly processed, but most just sit in queued. Before this issue started happening, items would process within a few seconds to a few minutes at most.

**Comment by giuliov** [comment]
@ajardolino3 can you share it again, maybe here on GitHub? Looks like the email reply lost the embedded pic.

**Comment by ajardolino3** [comment]
Sorry didn’t reply.  Looks like it just resolved itself.  Guessing an issue
with DevOps.
