### ISSUE TITLE
Feature Request: Enable bypassRules param on batch api calls.

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#22]
To eliminate some potential issues when using a rule with team projects using differing Processes the bypassRules param in the api calls can reduce the amount of issues in developing rules.

https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/WorkItemBatchUpdate?view=azure-devops-rest-4.1&viewFallbackFrom=vsts-rest-4.1

**Comment by pswetz** [comment]
on second thought maybe not, can have unknown effects.

**Comment by adu80** [comment]
Hello,

If it's an option when we add a rule, that would be great! For example, to fill in a read-only field.
We can add this command when we add a rule :
`add.rule [...] --bypassrule true`

**Comment by giuliov** [comment]
I would opt for a directive in the rule source than a creation-time option. Directives are described [here](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/rule-language.md#directives).

**Comment by adu80** [comment]
That would be more practical indeed. In any case, I am convinced of the usefulness of this development.
