### ISSUE TITLE
Problems with recent deployment for updated rule

### ISSUE THREAD

**Issue by jprettyman** [tfsaggregator/aggregator-cli#232]
I deployed an updated rule and the system now fails to run. I deployed to a test area and things worked fine. No errors on deployment and the rule runs fine using the invoke rule.
the message in the monitor for that instance is as follows: (I am at a loss on how to fix this.)

2021-02-22 16:34:16.891
Executing 'Functions.TaskRollUp' (Reason='This function was programmatically called via the host APIs.', Id=fc6e6aa5-a31b-499e-a678-f6237dcbe5d5)
Information
2021-02-22 16:34:17.229
Error
2021-02-22 16:34:17.229
Function compilation error
Error
2021-02-22 16:34:17.231
run.csx(3,1): warning AF006: The reference '../bin/aggregator-webshared.dll' is invalid. If you are attempting to add a framework reference, please remove the '.dll' file extension.
Warning
2021-02-22 16:34:17.289
run.csx(3,1): error CS0006: Metadata file '../bin/aggregator-webshared.dll' could not be found
Error
2021-02-22 16:34:17.290
run.csx(14,23): warning CS1702: Assuming assembly reference 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' used by 'aggregator-function' matches identity 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' of 'Microsoft.Extensions.Logging.Abstractions', you may need to supply runtime policy
Warning
2021-02-22 16:34:17.424
run.csx(15,31): error CS1061: 'HttpRequest' does not contain a definition for 'GetWebHookEvent' and no accessible extension method 'GetWebHookEvent' accepting a first argument of type 'HttpRequest' could be found (are you missing a using directive or an assembly reference?)
Error
2021-02-22 16:34:17.424
run.csx(16,24): warning CS1701: Assuming assembly reference 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' used by 'aggregator-function' matches identity 'Microsoft.AspNetCore.Mvc.Abstractions, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' of 'Microsoft.AspNetCore.Mvc.Abstractions', you may need to supply runtime policy
Warning
2021-02-22 16:34:17.508
Script compilation failed.
Error
2021-02-22 16:34:17.508
Executed 'Functions.TaskRollUp' (Failed, Id=fc6e6aa5-a31b-499e-a678-f6237dcbe5d5, Duration=545ms)
Error
2021-02-22 16:34:17.514
Script compilation failed.
Error

**Comment by giuliov** [comment]
The runtime version is older than the one referenced by the function. You can fix using the `update.instance` command.

**Comment by jprettyman** [comment]
I am also getting the following message each time I log in:
[2021-02-23 06:01:17Z] A new version (v1.0.1) of Aggregator CLI is available, please upgrade.
[2021-02-23 06:01:17Z] aggregator-cli v1.0.1 (build: 1.0.1.0 Release) (c) Copyright c TFS Aggregator Team

As far as I can tell, I have the latest. Is there anything I should do?
Joe Phy

________________________________

**Comment by giuliov** [comment]
The update message is a small bug.

I suggested to use the [`update.instance`](https://tfsaggregator.github.io/docs/v3/commands/instance-commands/#updateinstance) command to update the runtime of the function to fix the issue.

You should be able to see the runtime version in use running the [`list.instances`](https://tfsaggregator.github.io/docs/v3/commands/info-commands/#listinstances) command.

**Comment by jprettyman** [comment]
I am having so much trouble this week with the deployment. I verified that the current version is deployed. When I run a test in the Service hook for workitem.updated I get this message:

Status Code: 401
Reason Phrase: Unauthorized
HTTP Version: 1.1
Headers:
{
  Request-Context: appId=cid-v1:f77bc5ea-eeba-4afa-9cbe-4971ea62ea83
  Date: Tue, 23 Feb 2021 14:20:02 GMT
  Content-Length: 0
}
The aggregator has a correct PAT, I have authorization, just cannot get it to work. I am completely baffled.


Joe Phy

________________________________

**Comment by jprettyman** [comment]
Some messsages from applicaiton insight.

Inner exception System.EntryPointNotFoundException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:    at System.Collections.Generic.IDictionary`2.Add (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)    at aggregator.HttpExtensions.AddCustomHeaders (aggregator-webshared, Version=1.0.1.0, Culture=neutral, PublicKeyToken=nullaggregator-webshared, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null: /home/runner/work/aggregator-cli/aggregator-cli/src/aggregator-webshared/
​

   at Submission#0+<Run>d__1.MoveNext (f-TaskRollUp__1558282045, Version=0.0.0.0, Culture=neutral, PublicKeyToken=nullf-TaskRollUp__1558282045, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null: D:\home\site\wwwroot\TaskRollUp\run.csxf-TaskRollUp__1558282045, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null: 16)



Joe Phy

________________________________

**Comment by giuliov** [comment]
The Service hook uses Azure Function key for authentication: you can check if matches looking both at Azure Portal and the Service hook configuration

**Comment by jprettyman** [comment]
Yes, the function keys were different than what was in the service hooks. I updated them, and it fails with this error.

2021-02-23 14:21:46.183
Executing 'Functions.TaskRollUp' (Reason='This function was programmatically called via the host APIs.', Id=184fe680-73d9-470d-a88e-b15bd7e0ea08)
Information
2021-02-23 14:21:46.191
Aggregator v1.0.1 executing rule 'TaskRollUp'
Information
2021-02-23 14:21:46.264
Entry point was not found.
Error
2021-02-23 14:21:46.264
Executed 'Functions.TaskRollUp' (Failed, Id=184fe680-73d9-470d-a88e-b15bd7e0ea08, Duration=23ms)
Error
2021-02-23 14:21:46.267
Entry point was not found.


Joe Phy

________________________________

**Comment by jprettyman** [comment]
I wanted to provide an update on this issue. It is now working.
It appears that the update process was not being complete. The application said it was complete, but the files never made it to Azure. We ended up copying files manually and got it to run.
