### ISSUE TITLE
Docker image is not working

### ISSUE THREAD

**Issue by Dushki** [tfsaggregator/aggregator-cli#239]
while running a container docker fails with below error :
System.UnauthorizedAccessException: Access to the path '/secrets/apikeys.json' is denied. Any help is appreciated :)

**Comment by giuliov** [comment]
Probably the steps in https://tfsaggregator.github.io/docs/v3/setup/docker/ are not that clear.

1. You need to create an apikeys.json file, say `C:\aggregator\secrets\apikeys.json` with keys you [generate yourself](https://tfsaggregator.github.io/docs/v3/setup/docker/#define-the-set-of-valid-api-keys)
2. start the container mounting that folder e.g.
```
docker run --rm -it -p 5320:5320 -e Aggregator_VstsToken=********  -e ASPNETCORE_Kestrel__Certificates__Default__Password="********"  --mount type=bind,source=c:/aggregator/secrets/,target=c:/secrets --mount type=bind,source=c:/aggregator/rules/,target=c:/rules   tfsaggregator/aggregator3:latest
```

**Comment by Dushki** [comment]
Thanks giuliov 
However I have already tried with creating the keys in /secrets on Linux VM and mounted the volume but still same error.

**Comment by giuliov** [comment]
Have you checked with a simple container (e.g. busybox) if you can read the file in the mounted directory? If fails, then chmod / chown the dir on the host until you succeed

**Comment by Dushki** [comment]
Thanks Giuliov
I am able to run the docker container. However I am not able to find the next steps ? Can you please guide me on this?
I have gone through the documentation but it is not helping :(

**Comment by giuliov** [comment]
You are the first asking about the Docker scenario, so you are beta-testing the docs.
[This page](https://tfsaggregator.github.io/docs/v3/design/) can give you the overall picture, maybe.

Can you explain what you want to do next, what info you expect to find/read?

**Comment by Dushki** [comment]
Now we want to test the rules, how can we do it ?
Also we want to login to Azure and AzDo, do we need to install Aggregator CLI?

**Comment by giuliov** [comment]
Here is a checklist that should help you through the process

- [ ] pull the docker image
- [ ] prepare `apikeys.json`
- [ ] generate a valid certificate in `.pfx` format
- [ ] copy the two files above in a **secrets** directory on the docker host
- [ ] write the rule files (you can test them using the CLI)
- [ ] copy the rule files in a **rules** directory on the docker host
- [ ] run the container, mounting both the **secrets** and **rules** directories, and
defining the `Aggregator_SharedSecret` environment variable

Now the Aggregator instance running in the container is ready to serve.

- [ ] create a PAT in Azure DevOps
- [ ] download the CLI on any machine that can see both Azure DevOps and the Aggregat
Container
- [ ] set the `Aggregator_SharedSecret` environment variable
- [ ] use the `map.local.rule` to setup the WebHook Subscriptions in Azure DevOps

**Comment by Dushki** [comment]
Thank you @giuliov for the explanation.
I have performed all the step and am stuck at last point of executing map.local.rule command.
The command requires a parameter "target url" which Base Url of an existing Aggregator instance running in Docker. Can you please tell me how can i set up this or where i can find this.
I am using linux vm and generated the self signed certificate using openssl command.

**Comment by giuliov** [comment]
Have you tried the hostname of the machine where the container is running?
