### ISSUE TITLE
Issue with rollup type rules when PBI/bug only has 1 child task

### ISSUE THREAD

**Issue by rodgersk410** [tfsaggregator/aggregator-cli#25]
I added a simple rollup rule to calculate Completed Work / Original Estimate on PBI/bug.  This works for PBI's and bugs which have multiple child tasks but when there's only 1 child it fails.  Failures return 501 Not Implemented with error "The given key 'False' was not present in the dictionary.".  I think the Children relation is the issue.

Here's my rule for Original Estimate:
if (self.Parent != null)
{
	var parent = self.Parent;
	parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = parent.Children.Sum(task => Convert.ToDouble(task["Microsoft.VSTS.Scheduling.OriginalEstimate"]));
}

**Comment by giuliov** [comment]
Thanks for noticing: I am able to repro the issue and hope I can release a fix soon.

**Comment by manne** [comment]
I have the same issue. Version `v0.4.5-RC`

**Comment by manne** [comment]
we want to use `Aggregator` in production. this bug stops this plan.
@giuliov how can I support you to release a new version with this fix?

**Comment by manne** [comment]
@giuliov you have mail 📫

  `/%$§!sba`

**Comment by roizentner** [comment]
@giuliov Hi,
We're waiting for a release that fixes this bug.
Is there going to be one soon?
Thanks...

**Comment by giuliov** [comment]
I want to put one out after finishing #43 and #44. These aren't big but need some good testing.

**Comment by roizentner** [comment]
> I want to put one out after finishing #43 and #44. These aren't big but need some good testing.

OK cool, I'll keep waiting. Thanks!
