### ISSUE TITLE
Access is denied errors while executing rule

### ISSUE THREAD

**Issue by marnheus** [tfsaggregator/aggregator-cli#252]
# Steps to reproduce

Got the error in logs analytics, outside return code is 400.

## Expected behavior

Rule should execute

## Actual behavior

Rule fails with error 400

## Diagnostic logs

- Executing 'Functions.updateOwnerOrg' (Reason='This function was programmatically called via the host APIs.', Id=c927ea3e-311d-4e67-9a6a-140fb8037aa8)
- Aggregator v1.1.0 executing rule 'updateOwnerOrg'
- Connected to Azure DevOps
- Initial WorkItem 211555 retrieved from https://xxx.visualstudio.com/
- Rule 'updateOwnerOrg' failed: Access is denied. (0x80070005 (E_ACCESSDENIED))
## Environment
Latest version of aggregator.

**Comment by giuliov** [comment]
Hard to say more without additional information, e.g. what the rule is doing, which resources is trying to access, which permissions are tied to the PAT, and so on.
