### ISSUE TITLE
The application should be published as release

### ISSUE THREAD

**Issue by manne** [tfsaggregator/aggregator-cli#26]
**Expected**
The solution should be build with the release configuration.

**Actual**
The solution is built with the debug configuration.

![image](https://user-images.githubusercontent.com/80180/51526830-7bc23000-1e33-11e9-92f3-95ed31b23251.png)

```
[command]"C:\Program Files\dotnet\dotnet.exe" build D:\a\1\s\src\aggregator-cli.sln
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

[Link](https://dev.azure.com/TfsAggregator/Aggregator3/_build/results?buildId=352&view=logs&jobId=fd490c07-0b22-5182-fac9-6d67fe1e939b&taskId=5ce004ff-f36e-5243-994b-d03ca51fb277&lineStart=11&lineEnd=11&colStart=1&colEnd=113)

**Explanation**
the default value of  `dotnet build` for the option `configuration` is `Debug`. See [Docs dotnet build](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x)

**Implementation**
Append the option   `--configuration Release` to the `.NET Core` build task named `dotnet build` in [Azure Pipelines](https://dev.azure.com/TfsAggregator/Aggregator3/_build?definitionId=16)

**Hint**
If the YAML Azure Pipelines file is present in this repo, then I could create a PR for this matter. See [Create your first pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts)

Edit: added link to build log

**Comment by giuliov** [comment]
See https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.8
