### ISSUE TITLE
List.instances produces an error

### ISSUE THREAD

**Issue by manne** [tfsaggregator/aggregator-cli#27]
When calling `list.instances --resourceGroup XYZ --verbose` an error is produced
```
One or more errors occurred. (Invalid version.
Parameter name: version)
```
![image](https://user-images.githubusercontent.com/80180/51532405-512aa400-1e40-11e9-97a4-36ddb30f669c.png)

# Possible reason
Invoking `xyz.scm.azurewebsites.net/api/vfs/site/wwwroot/aggregator-manifest.ini` results in 
```
version=0.4.5-RC

```
Manually invoking 
```c#
	SemVersion.Parse(@"0.4.5-RC
").Dump();
```
in LINQPad results in an `ArgumentException` with the message
```
Invalid version.Parameter name: version
```

However manually invoking (pay attention to the missing last empty line)
```c#
	SemVersion.Parse(@"0.4.5-RC").Dump();
```
results in a correctly parsed version number

## Analysis
The file [src/aggregator-function/aggregator-manifest.ini](https://github.com/tfsaggregator/aggregator-cli/blob/782d3d1c7b793669503ba31d2f6d395b0acbbb26/src/aggregator-function/aggregator-manifest.ini) only contains one line. 
The file `aggregator-manifest.ini` in the deployment file `FunctionRuntime.zip` contains an empty last line

#### First
Update the PowerShell build task `Set version in aggregator-manifest.ini` to the last empty line is not produced
#### Second
Make the implementation of parsing the `aggregator-manifest.ini` file more robust

**Comment by manne** [comment]
@giuliov I can provide a PR for the 2nd solution
> Make the implementation of parsing the `aggregator-manifest.ini` file more robust

**Comment by giuliov** [comment]
Would be fantastic:this week and the next I am pretty busy with travelling and events.

Giulio Vian
Microsoft MVP, ALM DevOps Ranger
PSM I, MCTS, MCPD, MCSD1
mobile +353 89 2362452 | +39 348 2811203

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
