### ISSUE TITLE
Unable to list instances after a new instance has been successfully installed

### ISSUE THREAD

**Issue by cvialatte** [tfsaggregator/aggregator-cli#271]
# Steps to reproduce

Hi, 

I have created a new instance with this template :
{
  "ResourceGroupPrefix": "rg-",
  "ResourceGroupSuffix": "-prd-we",
  "FunctionAppPrefix": "func",
  "FunctionAppSuffix": "-prd-we",
  "HostingPlanPrefix": "hp-",
  "HostingPlanSuffix": "-prd-we",
  "AppInsightPrefix": "aip-",
  "AppInsightSuffix": "-prd-we",
  "StorageAccountPrefix": "strg",
  "StorageAccountSuffix": "prdwe"
}

The creation process wassuccessful. 
![image](https://user-images.githubusercontent.com/29101273/198059331-79ecaf7b-cf1c-4bd7-adf8-a7137c0e54e4.png)

Then I tried to add a new rule but I got an exception because no instance was found. Then I tried the command list.instances with many different options (no parameter, resource group, location...). I use the same account and parameters I used to create the instance.

PS C:\tools\aggregator-cli-win-x64> aggregator-cli list.instances --location westeurope
[2022-10-26 16:44:30Z] aggregator-cli v1.2.0 (build: 1.2.0.0 Release) (c) Copyright ¸ TFS Aggregator Team
[2022-10-26 16:44:30Z] Connected to subscription xxxxxxx
aggregator-cli : [2022-10-26 16:44:30Z] Deprecation notice: the resourceGroup option will be mandatory in a future version of Aggregator.
Au caractère Ligne:1 : 1
+ aggregator-cli list.instances --location westeurope
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([2022-10-26 16:... of Aggregator.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[2022-10-26 16:44:32Z] No aggregator instances found in westeurope Region.
[2022-10-26 16:44:32Z] list.instances Succeeded
[2022-10-26 16:44:32Z] Exiting with code 0

## Expected behavior

I should get the existing instance defintion

## Actual behavior

I get the following error:
[2022-10-26 16:44:32Z] No aggregator instances found in westeurope Region.
[2022-10-26 16:44:32Z] list.instances Succeeded
[2022-10-26 16:44:32Z] Exiting with code 0

If I try with the resource group name, I get the following error :

PS C:\tools\aggregator-cli-win-x64> aggregator-cli list.instances -g rg-tfsaggregator-prd-we
[2022-10-26 17:01:07Z] aggregator-cli v1.2.0 (build: 1.2.0.0 Release) (c) Copyright ¸ TFS Aggregator Team
[2022-10-26 17:01:08Z] Connected to subscription 2dea23f5-453a-4708-8a3e-11cfe9d71456
aggregator-cli : [2022-10-26 17:01:09Z] Object reference not set to an instance of an object.
Au caractère Ligne:1 : 1
+ aggregator-cli list.instances -g rg-tfsaggregator-prd-we
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([2022-10-26 17:...e of an object.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[2022-10-26 17:01:09Z] Exiting with code 99

## Diagnostic logs

> Please share diagnostics logs.  
> The logs may contain sensitive information, kindly review and mask those before sharing.

## Environment

I'm working with Azure and cli 1.2.0.0
![image](https://user-images.githubusercontent.com/29101273/198061251-154e34c2-d6a5-4eaf-966d-74bb94326154.png)

Best regards,

Christophe

**Comment by giuliov** [comment]
if you created the instance using a naming template, you must pass the template to all commands

**Comment by cvialatte** [comment]
Thank you, I didn't get that. It's working.
