### ISSUE TITLE
Verify rule before uploading

### ISSUE THREAD

**Issue by manne** [tfsaggregator/aggregator-cli#30]
Given a rule containing (only a parentheses)
```
(
```
When adding the rule
and mapping the rule
Then no errors occurs

# Actual
## Upload
No error occurs

## Runtime
When the rule is invoked
then following error occurs
```
 [Warning] Rule 'Invalid' failed: (1,2): error CS1733: Expected expression
```

# Expected
The CLI should not allow to upload invalid rules (according to the rule language), an error should be produced

**Comment by giuliov** [comment]
I like the suggestion but I think that the recently added `invoke.rule` command allows one to check for such error before uploading.
