### ISSUE TITLE
RuleEngine.ExecuteAsync() always sets State to Success

### ISSUE THREAD

**Issue by manne** [tfsaggregator/aggregator-cli#31]
Is the behavior of always succeeding regarding to `RuleEngine.State` on purpose? See line 114
https://github.com/tfsaggregator/aggregator-cli/blob/3916231c75994641fdeb73bab2e0f5762b79cbd2/src/aggregator-ruleng/RuleEngine.cs#L101-L114

**Comment by giuliov** [comment]
I bet no
