### ISSUE TITLE
Accessing Azure DevOps Web API/non exposed functionality

### ISSUE THREAD

**Issue by manne** [tfsaggregator/aggregator-cli#35]
## Rational
For a rule I have to know the category of a work item's state. This information is currently **not** exposed.
E.g. the category of the state `Done` of the work item type `Bug` of the process template `Scrum`

To get this information I can

a) write a constant mapping in the source code. Then I have to type a lot and customized process templates are not supported.
b) query the web/Rest API. Then customized process templates are supported.

I favor a).

## Question
How can accessing the web/Rest API achieved?
Answer: Something has to be implemented 😉

## Possible Implementations
a) Write a wrapper and expose it via WorkItemStore
```C#
public class WorkItemStore
{
    public async Task<string[]> GetWorkItemStatesAsync(string workItemType) { /* ..*/ }
}
```
b) Write a wrapper calls and expose it global type
c) Provide the possibility to extend the functionality (of a rule) without adjusting `Aggregator`. Directly access the Web API from the rule

**Comment by giuliov** [comment]
Another interesting scenario
> Is it possible to automatically create a branch when I drag a backlog item from "New" to "Approved" in Azure Devops?

**Comment by giuliov** [comment]
See https://tfsaggregator.github.io/docs/v3/rules/workitem/#backlogworkitemtypestates
