### ISSUE TITLE
Error when mapping rule - AzureWebJobsSecretStorageType does not support blob in functions v2

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#4]
Error thrown when trying to run map.rule

`Failed to retrieve function key: {"Message":"An error has occurred.","ExceptionMessage":"Runtime keys are stored on blob storage. This API doesn't support this configuration. Please change Environment variable AzureWebJobsSecretStorageType value to 'Files'. For more info, visit https://aka.ms/funcsecrets","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 141\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Functions.FunctionManager.<GetFunctionSecretsAsync>d__12.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 220\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Functions.FunctionController.<GetSecrets>d__12.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Functions\\FunctionController.cs:line 141"}`

**Comment by pswetz** [comment]
There was no setting that matched the name AzureWebJobsSecretStorageType so we had our cloud engineer add it to the app and it seemed to work, the event subscription did get added.

**Comment by AtisDimants** [comment]
I installed aggregator-cli today, and I have still this issue present. Has the fix been applied to master branch?

**Comment by pswetz** [comment]
>           I installed aggregator-cli today, and I have still this issue present. Has the fix been applied to master branch?

I do not believe it has, use the 0.4 branch. You should also use the 'pack' right click command on the function app and make sure to copy the zip that process creates into your cli directory so it uploads the correct one when creating an instance.

**Comment by giuliov** [comment]
@pswetz is right @AtisDimants : I am finishing work on the work item model before merging. I discovered some issues on the REST API (bug or by design, that's the question!) that have to be bypassed. In current state, the ability to create work items and/or linking them is limited.
