### ISSUE TITLE
Feature : possibility to apply filter on webhook

### ISSUE THREAD

**Issue by adu80** [tfsaggregator/aggregator-cli#45]
Hello,

To limit traffic, it would be nice to be able to specify filters with the "map.rules" command.
For example : 
`dotnet .\aggregator-cli.dll map.rule --rule xxx  --project "xxx" --event workitem.updated --resourceGroup xxx --instance xxx`

`--filtertype "Task" --filterfield "Microsoft.VSTS.Scheduling.OriginalEstimate"`

And in Azure DevOps :

![image](https://user-images.githubusercontent.com/47635488/52793191-77bdb280-306d-11e9-93d1-b1e222340c5b.png)

**Comment by giuliov** [comment]
Included in [v0.9.8](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.8).
