### ISSUE TITLE
unmap.rule fails with "given key 'url' was not present in the dictionary

### ISSUE THREAD

**Issue by DanHibbert** [tfsaggregator/aggregator-cli#49]
Hi,
I'm able to add rules to a TFS project but unable to delete them.  Could you point me in the right direction for this issue ?  I can't see where/why I add url to the args

This adds the rule successfully
`dotnet c:\dev\tools\aggregator\aggregator-cli\aggregator-cli.dll map.rule --verbose --project "Test Failures Count Test" --event workitem.created --instance Aggregator --resourceGroup Azure-DevOps-Aggregator --rule update_effort_fields`

But I'm unable to delete the rule
`dotnet c:\dev\tools\aggregator\aggregator-cli\aggregator-cli.dll unmap.rule --verbose --project "Test Failures Count Test" --event workitem.created --instance Aggregator --resourceGroup Azure-DevOps-Aggregator --rule update_effort_fields`

returns 
```
[2019-04-23 15:44:31Z] Reading Azure DevOps project data...
[2019-04-23 15:44:31Z] Project Test Failures Count Test data read.
[2019-04-23 15:44:31Z] One or more errors occurred. (The given key 'url' was not present in the dictionary.)
```
Thanks in advance !
Dan

**Comment by giuliov** [comment]
I see nothing wrong in principle and I assume you are using the most recent version, `0.9.1+3`.
Maybe you have additional subscriptions in the same project and those miss the `url` field?

**Comment by ericbehughes** [comment]
yes we did this issue and removing the extra subscriptions solved this issue

**Comment by torbennehmer** [comment]
@giuliov : Could you fix this, perhaps by ensuring that the url key is present in the dictionary before trying to query it? If you connect MS Teams with Dev Ops to get channel notifications, you'll automatically run into this error whenever TFS Aggregator tries to connect. The Teams Sevice Hooks do not have an URL and I can't hack around it either.

**Comment by giuliov** [comment]
I think this has been fixed a while ago, @torbennehmer can you recheck with latest version?

**Comment by torbennehmer** [comment]
@giuliov I have reproduced the error with the latest CLI release downloaded this morning: 

Aggregator CLI v0.9.1+3.Branch.master.Sha.8437ff414ecfd46da66ef5d3161f58818d9ab308 (build: 0.9.1.0 Debug) (c) TFS Aggregator Team

If I were to take a guess, I'd suspect the problem at this place:

src/aggregator-cli/Mappings/AggregatorMappings.cs, Method ListAsync:

![image](https://user-images.githubusercontent.com/2812067/60178167-1a0b5500-981b-11e9-8699-bf3a34b74fc8.png)

**Comment by giuliov** [comment]
I see. The `unmap` command should work, though.

**Comment by torbennehmer** [comment]
Sorry, that might be true, I haven't checked unmap specifically, when list.mappings failed with the same error, I went looking for a cause and found this open issue.

Should I create a new issue or will you track this in the scope of this one?

**Comment by giuliov** [comment]
Here is fine. I am only trying to scope the issue: I will sweep to the code looking for this issue.

**Comment by giuliov** [comment]
@torbennehmer I pushed a fix if you can try it

**Comment by conzyor34** [comment]
This is fixed for me now.
