### ISSUE TITLE
Function runtime unable to start

### ISSUE THREAD

**Issue by pswetz** [tfsaggregator/aggregator-cli#5]
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: The host.json file is missing the required 'version' property. See https://aka.ms/functions-hostjson for steps to migrate the configuration file. 
![runtime unable to start](https://user-images.githubusercontent.com/7573392/47370009-d3c18d00-d6b2-11e8-9984-6de15a31ef55.PNG)

**Comment by pswetz** [comment]
Confirmed latest host.json modification cleared the issue up.

` {
    "version": "2.0",
    "logging": {
        "fileLoggingMode": "always"
    }
}`

**Comment by giuliov** [comment]
This fix is already in committed code.
