### ISSUE TITLE
Confusing CLI command requirements for resource group and location

### ISSUE THREAD

**Issue by denious** [tfsaggregator/aggregator-cli#50]
The resource group parameter is not required, but the location parameter is required. As such, one would expect to be able to use any existing resource group and provide any location they desire. However, the supplied location argument is only used for new resource group creation, not the resources within (ex: app plan).

If a necessary resource is not available in the region of the resource group, the instance installation fails regardless of the input location.

In our case, all our resource groups are in WestUS. The deployment kept failing for Application Insights because the product is not available in the WestUS region. We had to dig through the code to figure out why - despite setting the instance location to WestUS2 - the CLI kept trying to use WestUS as the location for all the resources.

**Comment by giuliov** [comment]
Thanks for the feedback. I see that the code is not passing the value of the `location` parameter to the ARM template, so this latter uses the default value i.e. the region of the resource group. This is a simple bug to fix.
