### ISSUE TITLE
delete event fails 

### ISSUE THREAD

**Issue by ericbehughes** [tfsaggregator/aggregator-cli#51]
We are noticing in the log stream that the DELETE event still tries to retrieve the work item and fails since it no longer exists.

I don't think the rule even starts if the work item cannot be retrieved.

Thanks

https://github.com/tfsaggregator/aggregator-cli/blob/450d69483e7835da5e26719022225580fa054dad/src/aggregator-ruleng/RuleEngine.cs#L118

![image](https://user-images.githubusercontent.com/9938665/57558389-87d2ee80-734b-11e9-8cd2-22703c4829a9.png)

**Comment by giuliov** [comment]
Please confirm if #61 fixes this issue
