### ISSUE TITLE
Help Needed (No action is triggered)

### ISSUE THREAD

**Issue by prashanthbv12** [tfsaggregator/aggregator-cli#54]
I have done all the steps and Getting no errors in Azure log streaming.
I have uploaded below test rule in azure functions. 
When i close the child work item types eventually the parent has to get closed or show message. Nothing is happening. I am not getting any messages in Azure devops portal If Close parent or child. The states are also not getting transitioned automatically when I close child work items.
Please help

string message = "";
var parent = self.Parent;
if (parent != null)
{
    var children = parent.Children;
    if (children.All(c => c.State == "Closed"))
    {
        parent.State = "Closed";
        message = "Parent was closed";
    }
    else
    {
        message = "Parent was not closed";
    }
    parent.Description = parent.Description + " aggregator was here.";
}
return message;

**Comment by giuliov** [comment]
Check the mappings. You must map leaf types, like Task or Bug, events to this type of rule.

Giulio Vian
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by prashanthbv12** [comment]
Hello Giulio ,
Where I have to check the Mappings. Is it in some C# file?

Thanks,
Prashanth

**Comment by giuliov** [comment]
I mean to use the `list.mappings` command to check if you are sending the right events to the rule. If not use `unmap.rule` and `map.rule` commands to fix.

Giulio Vian
Microsoft MVP, ALM DevOps Ranger
PSM I, MCTS, MCPD, MCSD1
mobile +353 89 2362452 | +39 348 2811203

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by prashanthbv12** [comment]
Sorry I was making a simple mistake in states. There is no state in my work item type called as "Closed" I changed the rule to use "Done state". Now it is working.
Thanks for your prompt response giuliov . This tool is awesome :)
