### ISSUE TITLE
Let me specify a different region for Application Insights

### ISSUE THREAD

**Issue by igoravl** [tfsaggregator/aggregator-cli#55]
Application Insights is automatically provisioned as part of the creation of an instance. However, Application Insights is not available in all Azure datacenters, eventually leading to a failed deployment when deploying to e.g. Brazil South.

I want to be able to deploy my Aggregator instance closer to my Azure DevOps instance (e.g. deploying to Brazil South when connecting to Azure DevOps orgs hosted in Brazil), while at the same time deploying App Insights wherever it's available.

**Comment by giuliov** [comment]
Included in [v0.9.8](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.8).
