### ISSUE TITLE
Help needed to push some default text in to multi text field inside Azure Devops

### ISSUE THREAD

**Issue by prashanthbv12** [tfsaggregator/aggregator-cli#56]
Hello,

Whenever a new work item gets created want to push some default text into mult line text field area. Can this be done using CLI aggregator. If yes, can you please help me to with sample code

Thanks,
Prashanth

**Comment by giuliov** [comment]
It depends.
If you want something interactive, the proper solution is an extension written in JS/TS. Aggregator is a backend rule engine that is triggered after a work item is created or updated.

**Comment by prashanthbv12** [comment]
I got it.Thanks for your post. Also I was able to deploy rule related to Parent and child relationship using Test rule from your doc.
I have one more scenario working on. This is typically a workflow scenario which Azure devops does not have. 
Whenever an Epic is created with certain field set to Yes, It should automatically create some child tasks. can you please give me some inputs how can i write custom rule for achieving this scenario.

**Comment by giuliov** [comment]
You can find some basic examples in the tests, e.g.
```
var parentEpic = self;
var newChildStory = store.NewWorkItem("User Story");
newChildStory.Title = "Brand new";
parentEpic.Relations.AddChild(newChild);
```
Hope this helps and don't forget to close the issue later.

**Comment by prashanthbv12** [comment]
This helped. Thank you
