### ISSUE TITLE
Log stream duplicates all messages

### ISSUE THREAD

**Issue by torbennehmer** [tfsaggregator/aggregator-cli#57]
The log stream deployed by the CLI tool seems to show every message twice:

![image](https://user-images.githubusercontent.com/2812067/60179890-0bbf3800-981f-11e9-95d6-48591ce89150.png)

Any idea where I could look for a reason?

**Comment by giuliov** [comment]
I haven't drill down on the root cause of this behaviour.
Looking in AppInsight you see the traces only once, so it is a streaming issue; considering that Log streaming is designed for development and considered inadequate for production, I won't be much worried.

**Comment by torbennehmer** [comment]
Okay, in that case that's fine with me, thanks for the response.
