### ISSUE TITLE
Rule for customfield

### ISSUE THREAD

**Issue by prashanthbv12** [tfsaggregator/aggregator-cli#58]
I have new custom  field created by name TestMethodID and when I am trying to push some values to it by creating simple rule like below I am getting error. Please help

**Rule:**
.language=Csharp
if (self.WorkItemType == "Test Case")
{ 
  self.TestMethodID =1234;
}
return "Nothing to do";
Error:

'WorkItemWrapper' does not contain a definition for 'TestMethodID' and no accessible extension method 'TestMethodID' accepting a first argument of type 'WorkItemWrapper' could be found (are you missing a using directive or an assembly reference?)

**Comment by giuliov** [comment]
Custom fields have no predefined property, only the Core (aka Standard) fields.

You have to use the [`[`_field name_`]` syntax](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/rule-language.md#fields), which in your case means `self["TestMethodID"] =1234;`.

**Comment by prashanthbv12** [comment]
Thank you very much. It worked :) 

.language=Csharp
if (self.WorkItemType == "Test Case")
{ 
  self["Test Method ID"] = self["System.Id"];
}
return "Nothing to do";

**Comment by ben-garside** [comment]
I know this is closed, but it would be great if you could share how to get values from a custom field.

```
var value = self['customField'];
return value;
```

Returns the following:

```
One or more errors occurred. ((4,8): error CS0266: Cannot implicitly convert type 'object' to 'string'. An explicit conversion exists (are you missing a cast?))
```
