### ISSUE TITLE
Change item status in another organization

### ISSUE THREAD

**Issue by uweichelt** [tfsaggregator/aggregator-cli#63]
I tried to change Azure DevOps item status in an organization A that has no Azure directory assigned. The used Azure directory belongs to a Microsoft user which is a user in organization A. I was able to setup an Aggregator instance and an Aggregator Rule in Azure. I was also able to setup an Aggregator mapping via cli in Azure DevOps. When triggered the Azure DevOps Service Hook invokes the Aggregator Rule with the following output: [Warning] Rule 'itemstatus' failed: VS30063: You are not authorized to access https://xxx... (organization A).
Is this scenario simply not supported or do I miss anything?

**Comment by giuliov** [comment]
Not sure how clearly this is explained in the docs.

The PAT, set through the `login.ado` command, is saved along the Rule and used to call back Azure DevOps Service.
This means that your scenario is supported; probably you need to check/update the PAT which is stored in the Azure Function configuration. You can update the PAT using the `configure.instance` with the `authentication` option.

**Comment by uweichelt** [comment]
Thanks a lot! After updating the PAT it worked seamlessly.
