### ISSUE TITLE
TFS Aggregator deployment failed on Devops

### ISSUE THREAD

**Issue by jp108** [tfsaggregator/aggregator-cli#64]
Please find attached images - we are unable to deploy TFS Aggregator extension on Devops. Please help us to troubleshoot it. 

Error message is -
Deployment Error: The resource operation completed with terminal provisioning state 'Failed'! 

Also, checked with Microsoft support (https://developercommunity.visualstudio.com/content/problem/656535/change-states-and-add-rules-for-inheritence-work-i.html?childToView=661455#comment-661455). They having same issue so referred to raise issue here, 

Thank you!
Jolly Patel

**Comment by giuliov** [comment]
We have two Aggregator projects: the classic TFS Aggregator Server Plugin for the on-premise scenario and this new Aggregator CLI for Azure DevOps Service.

I guess you tried to use the https://github.com/tfsaggregator/tfsaggregator-webhooks which we deprecated. I had trouble retiring it from the Marketplace last time I tried, so you may still find it.

Use [Aggregator CLI](https://github.com/tfsaggregator/aggregator-cli/releases) for Azure DevOps Service. It requires:

- .Net Core 2.2
- credentials for an Azure Subscription
- a PAT for Azure DevOps

Let me know if you have additional questions.
