### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by ben-garside** [tfsaggregator/aggregator-cli#65]
SImilar to #58 which has been closed. It would be great if you could share how to get values from a custom field.

```
.lang=C#
var value = self['customField'];
return value;
```

Returns the following:

```
One or more errors occurred. ((4,8): error CS0266: Cannot implicitly convert type 'object' to 'string'. An explicit conversion exists (are you missing a cast?))
```

**Comment by giuliov** [comment]
Thanks for asking, we should expose an helper function like the one offered in v2.

In the mean time, you can simply cast the field value to a string or number or date:
```
var customField1 = (string)self['stringCustomField1'];
var customField2 = (decimal)self['numericCustomField2'];
var customField3 = (int)self['idCustomField3'];
var customField4 = (DateTime)self['dateCustomField4'];
```
depending on the field type.

**Comment by ben-garside** [comment]
Fantastic, thank you very much for your reply. That worked 👍

**Comment by giuliov** [comment]
Next release will offer a `GetFieldValue` function which handles conversion and default.
Closing this issue.
