### ISSUE TITLE
How to get values of Parent task in Child task...

### ISSUE THREAD

**Issue by KamranAslamBhatti** [tfsaggregator/aggregator-cli#66]
Hi,
I want to get field values (e.g. DueDate of Parent task) into Child task, it is like when a child task will be created its DueDate will be Auto filled to same as Parent task dueDate is.
I am using following code for this but it is not working, it is giving me following error under Service Hook:
- 503 - Not Implemented
Sample Code:

.lang=C#
using System;
using System.Collections;
using System.Collections.Generic;

string message = "";
var parent = self.Parent;
if (parent != null)
{
    var children = parent.Children;
    self["System.DueDate"] = parent["System.DueDate"];
}

**Comment by KamranAslamBhatti** [comment]
I also tried following code too but it also did not work.

.lang=C#
using System;
using System.Collections;
using System.Collections.Generic;

string message = "";
var parent = self.Parent;
if (parent != null)
{
self.Description = "Aggregator was here.";
self["DueDate"] = parent["DueDate"];
self.Title = "Aggregator edit title";
}

**Comment by giuliov** [comment]
Remove the using statements or replace them with `.import=` directives, e.g. `using System;` becomes `.import=System`.

**Comment by KamranAslamBhatti** [comment]
Hi giuliov,
Thanks for your prompt response, I tried it but it did not work :( and give me same error. I replace using with .import and tried and also I totally remove the using and then also tried and get the same following error:
-501 Not Implemented

Following is the update code:
![Error](https://user-images.githubusercontent.com/48288316/63179899-c1825800-c012-11e9-9e2e-4c384e917149.png)


.lang=C#
.import=System
.import=System.Collections
.import=System.Collections.Generic

string message = "";
var parent = self.Parent;
if (parent != null)
{
self.Description = "Aggregator was here.";
self["DueDate"] = self.Parent["DueDate"];
self.Title = "Aggregator edit title";
}

**Comment by KamranAslamBhatti** [comment]
Just want to update that following code works fine, this code is for a single task like edit a single tasks fields from aggregator rule, however when I run above mentioned code then it gives Not Implemented error as I mentioned above.

.lang=C#

string message = "";
self.Description = "Aggregator was here.";
self.Title = "Aggregator edit title";
self["DueDate"] = DateTime.Now;

**Comment by giuliov** [comment]
Need to check the details, but these 4 lines are completely redundant for your code
```
.lang=C#
.import=System
.import=System.Collections
.import=System.Collections.Generic
```
C#, System and System.Collections.Generic are defaults.

I guess you have the error because `.import=System.Collections` is not a default and it has no matching `.reference=System.Collections.NonGeneric.dll` (and probably `.reference=System.Runtime.Extensions.dll` but not sure).

Our defaults cover the most common scenarios, the use of directives like `.import` or `.reference` is for advanced scenarios. You do not need them in any of the examples displayed in documentation.

**Comment by KamranAslamBhatti** [comment]
Hi giuliov, I removed the redundant lines but still the same error. Following is the code:

string message = "";
var parent = self.Parent;
if (parent != null)
{
self.Description = "Aggregator was here.";
self["DueDate"] = parent["DueDate"];
self.Title = "Aggregator edit title";
}

**Comment by giuliov** [comment]
You should share more information, especially logs. See https://github.com/tfsaggregator/aggregator-cli#troubleshooting for starting.

**Comment by KamranAslamBhatti** [comment]
Thanks Giuliov, I followed above link and following are the logs which did have error information (bold text) but not sure how can I fix it:

2019-08-20T11:51:06.974 [Information] Connected to Azure DevOps
2019-08-20T11:51:06.974 [Information] Connected to Azure DevOps
2019-08-20T11:51:10.501 [Information] Loading workitem 103
2019-08-20T11:51:10.501 [Information] Loading workitem 103
2019-08-20T11:51:10.973 [Information] Initial WorkItem 103 retrieved from https://dev.azure.com/TFSAggregatorTesting/
2019-08-20T11:51:10.973 [Information] Executing Rule...
2019-08-20T11:51:10.973 [Information] Initial WorkItem 103 retrieved from https://dev.azure.com/TFSAggregatorTesting/
2019-08-20T11:51:10.973 [Information] Executing Rule...
2019-08-20T11:51:24.122 [Information] Loading workitem 50
**2019-08-20T11:51:24.228 [Information] Rule succeeded with no return value**
2019-08-20T11:51:24.485 [Information] Found a request to update workitem 103 in TestProject_Aggregator_Testing
**2019-08-20T11:51:24.539 [Warning] Rule 'AutoUpdateDates' failed: Value cannot be null.
Parameter name: o**
2019-08-20T11:51:24.548 [Information] Executed 'Functions.AutoUpdateDates' (Succeeded, Id=085xxxxxxfa)
2019-08-20T11:51:24.123 [Information] Loading workitem 50
2019-08-20T11:51:24.228 [Information] Rule succeeded with no return value
2019-08-20T11:51:24.485 [Information] Found a request to update workitem 103 in TestProject_Aggregator_Testing
**2019-08-20T11:51:24.539 [Warning] Rule 'AutoUpdateDates' failed: Value cannot be null.
Parameter name: o**
2019-08-20T11:51:24.548 [Information] Executed 'Functions.AutoUpdateDates' (Succeeded, Id=0854c18b-xxxx)

**Comment by giuliov** [comment]
You should use the reference name for fields, in your case `Microsoft.VSTS.Scheduling.DueDate`.

**Comment by KamranAslamBhatti** [comment]
Giuliov,
I used the refrence name of fields like following but still same error:

.lang=C#
using System;
using System.Collections;
using System.Collections.Generic;

string message = "";
var parent = self.Parent;
if (parent != null)
{
self.Description = "Aggregator was here.";
self["WorkItemWrapper.Microsoft.VSTS.Scheduling.DueDate"] = parent["WorkItemWrapper.Microsoft.VSTS.Scheduling.DueDate"];
self.Title = "Aggregator edit title";
}

**Comment by giuliov** [comment]
I try to be patient here.

I already explained that you cannot use `using` but it is there in your code. I said to use `Microsoft.VSTS.Scheduling.DueDate` but your code shows `WorkItemWrapper.Microsoft.VSTS.Scheduling.DueDate`.

A final tip: have you checked if the work items types you are using have such field?

**Comment by KamranAslamBhatti** [comment]
Thanks Giuliov for your help, the issue solved :), I am now able to access the values between parent and child tasks.
Thanks alot once again for all your replies which really helps me to fix the issue.
