### ISSUE TITLE
Update frequency to minimize

### ISSUE THREAD

**Issue by KamranAslamBhatti** [tfsaggregator/aggregator-cli#69]
Hi,
I want to ask is there a way we can reduce the time it took to run the aggregator-cli script against an event, e.g. I have written a code to update the field (Notes) of a task to a standard value when any work item will be created. This is something like whenever a work item will be created its Notes field will have a default/pre-defined value.

I noticed that when I create work item it took between 10-25 seconds to update the field value.
I want to ask is there any configuration setting where we can reduce this time to something like 5 seconds?

Thanks,
Kamran

**Comment by giuliov** [comment]
Short answer: not really.
Long answer:
Azure DevOps use a non-predictable-timing internal queue to generate events. What you might do is optimise the receiving side, i.e. the Azure Function.
I can think of these directions:

1. change the plan from Dynamic (Y) to Premium (P2V2 or similar)
2. optimise the Aggregator code so it caches the Rosalyn interpreted code (a PR would be appreciated)

**Comment by KamranAslamBhatti** [comment]
Thanks giuliov for the prompt response.

**Comment by giuliov** [comment]
BTW you can set the plan using the `--hostingPlanTier` and `--hostingPlanSku` options of `install.instance` verb.

**Comment by giuliov** [comment]
also make sure that the Aggregator instance is in the same Azure Region as you Azure DevOps organization.
