### ISSUE TITLE
Wrapping up for 1.0

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/aggregator-cli#70]
This issue tracks the discussion for the 1.0 release.

My (@giuliov) opinion on remaining issues:
 - must be solved before release: #55, #45, #26 
 - nice to have, but can be postponed after 1.0: #62, #40, #35, #14

Am I missing anything important, @jessehouwing @BobSilent @pswetz @manne ?

**Comment by BobSilent** [comment]
Sounds good for me

for #35 I already have something prepared, not the whole thing yet but work in progress
#45 and #62 are the ones I will focus next.

#14 would be good, but can also be part of a 2.0 afterwards.

**Comment by giuliov** [comment]
I already implemented in my branch all three
________________________________

**Comment by BobSilent** [comment]
@giuliov so I would go for #62 now and I would like to have a look at #14. 
for #14 i will read and add some ideas we can disucss in #14.

**Comment by giuliov** [comment]
Included in [v0.9.8](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.8).
