### ISSUE TITLE
How to get previous value of any field...

### ISSUE THREAD

**Issue by KamranAslamBhatti** [tfsaggregator/aggregator-cli#78]
Hi,
I want to know is there a way we can get field value which was assigned to a field before it update. e.g. if a date field value is changed/updated from 09/01/2019 to 09/10/2019 then I can get the latest value 09/10/2019 of field easily via following code:
Var Datevalue = self["Microsoft.VSTS.Scheduling.TargetDate"];

But I want to get value 09/01/2019 means the value which was assigned to a field before it was updated to new value.

Thanks,
Kamran

**Comment by KamranAslamBhatti** [comment]
Please ignore as my issue resolved with PreviousRevision property.

Thanks,
Kamran

**Comment by BobSilent** [comment]
You can also use `selfChanges` in an workitem update event
e.g. 
`selfChanges.Fields["Microsoft.VSTS.Scheduling.TargetDate"]`
there you have the property `OldValue` `NewValue` which could help you

for details see [work item update example](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/rule-examples.md#work-item-update)
[Language description](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/rule-language.md#workitem-changes)

The difference is just speed, accessing PreviousRevision needs a server round trip

**Comment by KamranAslamBhatti** [comment]
Hi BobSilent,
Thanks for the above code as this is more suitable than PreviousRevision. However I am getting following error when try to use it, do I need to import some namespaces?

var TDateOld =  selfChanges.Fields["Microsoft.VSTS.Scheduling.TargetDate"];
var predecessorOrignalDate = DateTime.Parse(TDateOld.OldValue.ToString());
--Error The name 'selfChanges' does not exist in the current context

Thanks,
Kamran

**Comment by giuliov** [comment]
We haven't released this version, yet. You can build and deploy the new runtime yourself.

**Comment by KamranAslamBhatti** [comment]
Thanks giuliov for the prompt reply.

**Comment by Hupka** [comment]
Hello @giuliov I stumpled over your reply here and realized this was the reason for my confusion. When do you plan to release the new version? Compiling the source gets complicated on my Mac... :-(

**Comment by giuliov** [comment]
@Hupka I drafted a [release](https://github.com/tfsaggregator/aggregator-cli/releases/tag/untagged-89acbf1f462a32ddf356) but was busy with personal stuff so couldn't finalise; hope to catch up soon. I aim at wrapping up and releasing 1.0 before end of year.
