### ISSUE TITLE
Example failures

### ISSUE THREAD

**Issue by johnradford** [tfsaggregator/aggregator-cli#79]
# Steps to reproduce

Copying the update rule from the example folder.  I have an error 501 not implemented,  I am trying to compare a custom field before and after update, I will then use the original value to ensure I update children with the field only if the child had the original value.  

I am getting a not implemented 501 error,  Is there something from the documentation,  Have I missed something?

**Comment by BobSilent** [comment]
Can you add a link to the example or paste the sample code here, which does not work.

**Comment by johnradford** [comment]
var parent = self;

// test to avoid infinite loop
if (parent.WorkItemType == "Task") {
    return "No root type";
}

var children = parent.Children;
// test to avoid infinite loop
if (!children.Any(c => c.Title == "Brand new child"))
{
    var newChild = store.NewWorkItem("Task");
    newChild.Title = "Brand new child";
    parent.Relations.AddChild(newChild);

    return "Item added";
}

return parent.Title;

I am trying to create a number of tasks against enhancement requests once they have been raised.  ie. analysis,development, documentation and test.

Thank you

**Comment by giuliov** [comment]
The code looks ok, so we should inspect configuration. You should see a detailed error message in the response (in Azure DevOps go to Settings / Service Hooks, open the event History and look into the failing call)
You can gather further information by monitoring execution (see [here](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/build-and-test.md#debug-aggregator-runtime-live-azure-function) and [here](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/production.md#production-monitoring)).

**Comment by johnradford** [comment]
Status Code: 501
Reason Phrase: Not Implemented
HTTP Version: 1.1
Headers:
{
  Date: Fri, 11 Oct 2019 09:58:49 GMT
  Content-Length: 12
  Content-Type: text/plain; charset=utf-8
}

Thank you this was the response.  I will attempt to gain access to the azure ( currently held by administrator)

**Comment by johnradford** [comment]
Thank you for your responses.  after gaining access to the ado functions online and using the monitor I could determine that there were some mandatory fields that were missing
