### ISSUE TITLE
Query on selfChanges.keyContains

### ISSUE THREAD

**Issue by johnradford** [tfsaggregator/aggregator-cli#80]
Trying to code to check whether a state has been updated and therefore create default tasks when an enhancement moves to commited. 

I have the following code in the rule.

    if (selfChanges.Fields.ContainsKey("System.State"))
        {
        return "Status Updated";
        }

when trying to upload I get an error 
Errors in the rule file rules\ServiceDeskRefWIP.rule:
(123,9): error CS0103: The name 'selfChanges' does not exist in the current context

**Comment by giuliov** [comment]
`selfChanges` is merged to master but you have to build and deploy the updated runtime in the `install.instance` command using the `sourceUrl` option

**Comment by johnradford** [comment]
Are there any plans for a new release. being new to c# is the source url as simple as where the solution is held c:\..\source\aggregator-cli\.  if not what is required to build and package the solution please

**Comment by giuliov** [comment]
I have plans, but been busy lately. Hope I can hand out a Christmas gift.
In case you want to go on your own, there are some notes on building and deploying in the `doc` folder.

**Comment by johnradford** [comment]
I've tried but my area is more databases and sql so I think I'll wait for the release,  Thank you,  that will be a useful Christmas present

**Comment by giuliov** [comment]
Please check [v0.9.8](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.8).

**Comment by johnradford** [comment]
Giulio

Thank you for the release.  I’ve been trying to download the windows zip but it’s failing. However I’m unable to open the zip 7zip states that the format is corrupted

Regards.


John Radford
Business Intelligence Lead
[EMAIL]john.radford@rotork.com
Rotork Group, Brassmill Lane, Bath, BA1 3JQ, England
[Untitled-5]

**Comment by giuliov** [comment]
Just tested on my Win machine and works fine. Do you have more details?
