### ISSUE TITLE
New directive : bypassrule

### ISSUE THREAD

**Issue by adu80** [tfsaggregator/aggregator-cli#83]
Hello,

In a rule, have possibility to specify this directive :
**.bypassrule=true**

In this case, when a workitem is update, the process rules are ignored.

Thank you.

**Comment by giuliov** [comment]
Can you elaborate your scenario more? I can easily imagine one of the following two scenarios and the solution using existing features:

1. you do not want trigger a rule for a specific event -- disable or remove the mapping in the DevOps Project
2. you want to disable a rule altoghether -- disable the rule using Aggregator CLI or any Azure interface like Portal, Az CLI etc.

Looking forward for your reply

**Comment by adu80** [comment]
Sorry I didn't explain myself well, I talk about the possibility to use the parameter **bypassRules** in [this method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.workitemtracking.webapi.workitemtrackinghttpclientbase.createworkitemasync?view=azure-devops-dotnet). So, we can update a workitem and Azure DevOps process rules can be ignored.

In my case, I made a mandatory field but in tfsaggregator I want to update a workitem without being obliged to fill it in (this must be done by the user).

**Comment by giuliov** [comment]
I see: adding backlog labels

**Comment by BobSilent** [comment]
should this be an option or always valid?

BUT: Having this Option set to true, the provided PAT needs to have the appropriate permission to bypass rule validation (see also #74).

**Comment by adu80** [comment]
I understand your point of view, but as you say, if it's always valid, it means giving an additional right all the time, which managers may not want ?
I'm divided. Personally, I wouldn't mind if it was still activated.

**Comment by sirtwist** [comment]
Just sent PR #228 for this ... I needed this functionality as well.

**Comment by giuliov** [comment]
Feature added in [1.1](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v1.1.0)
