### ISSUE TITLE
Directives make Roslyn Diagnostic Locations incorrect

### ISSUE THREAD

**Issue by andersforsgren** [tfsaggregator/aggregator-cli#84]
# Steps to reproduce

A rule source with 

    .reference="Lib"    // line 1
    return "Hello world"    // line 2 (With missing semicolon)

Will produce a roslyn diagnostic for the missing semicolon, but with location on Line 1, because the directive line is stripped before the remaining lines are compiled to a csharpscript.
  
## Expected behavior

The compiler diagnostic in the above example is for Line 2.
That is, roslyn diagnostics have locations that make sense in the overall buffer including directives, because that is the buffer the user is likely to edit in a user interface.

## Actual behavior

Roslyn diagnostics have locations that are only correct in the buffer after the directive lines with leading dots are removed.

I speculate that this could be easy to fix by simply _including the directive lines commented out_ to the CSharpScript, instead of removing them. So instead of sending this array of 1 line

    return Hello world

This array of 2 lines should be the Script source:

    //.reference="Lib"
    return Hello world 

I'll attempt to make a PR with this solution if it looks acceptable.

## Environment

v0.9.2-35-ga24ff33

**Comment by giuliov** [comment]
Nice catch. Added item to backlog through labels

**Comment by andersforsgren** [comment]
I'll submit a PR for this shortly

**Comment by giuliov** [comment]
Included in [v0.9.8](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.8).
