### ISSUE TITLE
Loop thru all child tasks and assign values to each child task

### ISSUE THREAD

**Issue by KamranAslamBhatti** [tfsaggregator/aggregator-cli#87]
Hi,
I want to loop all child tasks of a parent task and then assign value to each child task after some calculations, following is the code which I write for this but its not working, the code did run without any issues and no errors but the value does not assign value to child tasks. Could you please let me know how can we achieve this.
```
var allWorkItemLinks = self.RelationLinks;

 foreach(var childLink in allWorkItemLinks.Where(link => string.Equals("System.LinkTypes.Dependency-Forward", link.Rel)))
 {
    // get work item id from link and parse to integer
    var id = int.Parse(childLink .Url.Split('/').Last());

    // now load the workitem
    var child = store.GetWorkItem(id);

   //Getting child and parent task dates
   var childDate =DateTime.Parse(child["Microsoft.VSTS.Scheduling.TargetDate"].ToString());
   var ParentOriginalDate =DateTime.Parse(self.PreviousRevision["Microsoft.VSTS.Scheduling.TargetDate"].ToString());
   var ParentUpdatedDate =DateTime.Parse(self["Microsoft.VSTS.Scheduling.TargetDate"].ToString());
 
 // Updating child task dates
   int days = (DateTime.Parse(ParentUpdatedDate.ToString()) - DateTime.Parse(ParentOriginalDate.ToString())).Days;
   if (days>0)
   {
child["Microsoft.VSTS.Scheduling.TargetDate"]=DateTime.Parse(childDate.ToString()).AddDays(days);
   } 
   if (days<0)
   {
child["Microsoft.VSTS.Scheduling.TargetDate"]=DateTime.Parse(childDate.ToString()).AddDays(days);
   }
 }
 ```
Thanks,
Kamran

**Comment by BobSilent** [comment]
`System.LinkTypes.Dependency-Forward` is not Child Relation, it is `Successor`

you can simplify your code like that

```
            foreach (var child in self.Children)
            {
                //Getting child and parent task dates
                var childDate = DateTime.Parse(child["Microsoft.VSTS.Scheduling.TargetDate"].ToString());
                var ParentOriginalDate = DateTime.Parse(self.PreviousRevision["Microsoft.VSTS.Scheduling.TargetDate"].ToString());
                var ParentUpdatedDate = DateTime.Parse(self["Microsoft.VSTS.Scheduling.TargetDate"].ToString());

                // Updating child task dates
                int days = (DateTime.Parse(ParentUpdatedDate.ToString()) - DateTime.Parse(ParentOriginalDate.ToString())).Days;
                if (days > 0)
                {
                    child["Microsoft.VSTS.Scheduling.TargetDate"] = DateTime.Parse(childDate.ToString()).AddDays(days);
                }
                if (days < 0)
                {
                    child["Microsoft.VSTS.Scheduling.TargetDate"] = DateTime.Parse(childDate.ToString()).AddDays(days);
                }
            }
```

if this does not already help, you can start with a more simple rule like that
```
foreach (var child in self.Children)
{
    child.Title = "Updated: " + child.Title;
}
```
and see if it updates the children titles

**Comment by KamranAslamBhatti** [comment]
Bob, thanks for the prompt reply.
I am getting "Object reference not set to an instance of an object. " error with the following simple code. The fields (TargetDate and Description) I have already verified and they are correctly referenced in the code.

foreach (var child in self.Children)
 {
   var childDate =child["Microsoft.VSTS.Scheduling.TargetDate"].ToString();
   child["System.Description"] = childDate.ToString();
 }

Can we get the child tasks values in loop via following statement as I suspect it is causing the error:
child["Microsoft.VSTS.Scheduling.TargetDate"].ToString();

**Comment by BobSilent** [comment]
first of all `self.Children` are not only Task Work Items, it can be any work item linked as Child

if you want only Tasks you need something like `self.Children.Where(c => string.Equals("Task", c.WorkItemType))`

`var childDate =child["Microsoft.VSTS.Scheduling.TargetDate"].ToString();` can lead to `Object reference not set to an instance of an object.`
as if `child["Microsoft.VSTS.Scheduling.TargetDate"]` has no value set yet, you get null, so you should do something like that `var childDate = self["Microsoft.VSTS.Scheduling.TargetDate"]?.ToString() ?? DateTime.Now.ToString("u");`

only call `?.ToString()` if workitem field is not null, otherwise take a default value  e.g. `DateTime.Now.ToString("u")`

**Comment by KamranAslamBhatti** [comment]
Thanks alot Bob it's working now :)
