### ISSUE TITLE
Instance not being found in Azure

### ISSUE THREAD

**Issue by RSMJreck** [tfsaggregator/aggregator-cli#90]
I recently installed this into Azure, however I'm getting inconsistent results when looking for instances to upload rules to. As an example, see attached image. Is there something specific for how it looks for instances that I might be missing?
![aggregator](https://user-images.githubusercontent.com/58529520/71293407-ec6f1680-233a-11ea-86e4-22c8eec0028d.png)

**Comment by giuliov** [comment]
Probably you should add the `--resourceGroup` option to the **add.rule** command.
