### ISSUE TITLE
Compiling rules failed with new version

### ISSUE THREAD

**Issue by adu80** [tfsaggregator/aggregator-cli#93]
Hi,

I've upgraded to v0.9.8 (install.instance and update.rule) and now i have this error for all call :

```
2020-01-09T10:10:24.718 [Error] Function compilation errorMicrosoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) 
at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader 1.GetFunctionTargetAsync[T](Int32 attemptCount) 
at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\FunctionLoader.cs : 55
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) 
at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2020-01-09T10:10:24.782 [Error] run.csx(10,23): error CS1705: Assembly 'aggregator-function' with identity 'aggregator-function, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Logging.Abstractions' with identity 'Microsoft.Extensions.Logging.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

Anyone can help me ?

**Comment by MOReson** [comment]
I've been getting the same error. So far, I haven't found a solution.
Trying to dig into this a little more today.

**Comment by schnuderl** [comment]
same with me

**Comment by adu80** [comment]
Thanks all, I feel less lonely.
For information, I tried to remove and re-add all rule, to change runtime version of the app (2->3) without success (same as schnuderl). I checked files, DLLs and configuration, I can't find the reference to the version 2.2

**Comment by giuliov** [comment]
Looks like an issue with dependencies, but I also noticed a build issue with versioning.

**Comment by BobSilent** [comment]
@giuliov the aggregator-function where update to V3 but he instance template is still V2

https://github.com/tfsaggregator/aggregator-cli/blob/d25e1b8284d958c786ac7116f816da7e5fa011f2/src/aggregator-cli/Instances/instance-template.json#L144-L147

This leads to a version conflict, during runtime we get the old V2 dependencies.

So changing the runtime version of a a function instance to V3 should fix the issue.
`Runtime version: 3.0.12939.0 (~3)`

https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version

**Comment by schnuderl** [comment]
@BobSilent hm, please consider my first comment, "If i change the Runtime Version of the Function WebApp in Azure to V3, then this error is gone but a lot of other error occure in my Rules, meaning strange ones like having a empty rule fails with a stringcast error, etc."

**Comment by BobSilent** [comment]
@schnuderl I know, then you are facing: #91, #92. Therefore a PR exists #94

**Comment by schnuderl** [comment]
@BobSilent ok,all clear. thank you for the clarification.

**Comment by BobSilent** [comment]
yeah, the issue is a little bit larger and that is the confusing part.
it took me some time, to understand the whole scenario and get the relations between them.

**Comment by adu80** [comment]
@BobSilent Thanks a lot for your investigations and your futur fixes.

**Comment by schnuderl** [comment]
hi. what would you suggest how i should proceed @BobSilent ? tryout PR 108 (but there is a comment it gives an error)? thank you

**Comment by BobSilent** [comment]
Sorry for long time to further information, but was quite busy with looking at my sick family ;)

PR #108 is work in progress, which means you cannot simply use it without a little bit of know how.

PR #108 brings some of the already discussed things to automatically migrate your aggregator-cli instance to Azure Functions V3.
Therefore I added a new command to do the migration, i have to say that i currently did not had a chance to discuss this a little bit with @giuliov therefore I also cannot say if it will finally make it into the master (as it is right now) - I would assume that we will have some kind of update mechanism, as in current implementation the runtime update is implicitly done with `update.rule` command.
But for azure v3 we need a little bit more "than just updating the runtime binaries".
"Hidding" this process behind an `update.rule` is from my perspective not a good way.
All in all, it automates some things like changing runtime to V3

To shorten it a little bit: 
- if you want to have a running instance, or if you are not familiar with manually doing things in azure functions
- if you know how to build the source and are a little bit technical interested i would say please help me in test it and give it a try.

As the new command `update.instance` can not really do the update (we have not released the version) you need to build the source, create the `FunctionRuntime.zip` and then call the `update.instance` command.
The command output should write something like
`Using local cached runtime package ...`
then it will take the correct runtime package, do the update and migration steps for your azure functions.
Afterwards you should be able to use the previously build aggregator-cli to add/update your rules, as before.

**Comment by schnuderl** [comment]
thank you for your answer @BobSilent . ok, i will try, but high probability that i get stuck somewhere, then at least i let you know that i gave up ;-)
