### ISSUE TITLE
State based Transition

### ISSUE THREAD

**Issue by prashanthbv12** [tfsaggregator/aggregator-cli#95]
Since we have come long way, As i requested this feature earlier. Can something like below can be implemented.

My goal is when ever a state of a PBI is new, it should display only certain values in sub state(custom field) and when it is approved other values should display . I have written rule like below but is not working. Please help
.language=Csharp
if (self.WorkItemType == "Product Backlog Item")
{
if (self.State == "New")
{
self["Sub State of PBI"] = "Proposed,Ready,Approved";
}

if (self.State == "Approved")
{
self["Sub State of PBI"] = "Approved,Awaiting Test";
}
}

return "Nothing to do";

**Comment by BobSilent** [comment]
Same as #76

**Comment by prashanthbv12** [comment]
Can we now start writing rule now if changes are done in particular filed system.state, then show some values in the other field (example substate mentioned above)? 
Is is it possible to create rule something like this. Please help. 

if (selfChanges.Fields.ContainsKey("System.state"))
